name: 'Rust & Forc Setup'

inputs:
  rust-version:
    default: 1.73.0

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-version }}
        components: clippy, rustfmt

    - name: Init cache
      uses: Swatinem/rust-cache@v2

    - name: Install Fuel toolchain
      uses: FuelLabs/action-fuel-toolchain@v0.6.0
      with:
        name: custom
        components: forc@0.47.0, fuel-core@0.20.8
