[workspace]
resolver = "2"
members = [
    "packages/message-predicates/contract-message-predicate",
    "packages/fungible-token/bridge-fungible-token",
    "packages/risc0/core",
    "packages/risc0/host",
    "packages/risc0/test",
    "packages/risc0/methods/guest"
]

[workspace.package]
authors = ["Fuel Labs <contact@fuel.sh>"]
categories = ["cryptography::cryptocurrencies"]
edition = "2021"
homepage = "https://fuel.network/"
keywords = ["blockchain", "cryptocurrencies"]
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuel-bridge"
version = "0.3.0"
rust-version = "1.72.0"

[workspace.dependencies]
# Dependencies from fuel-vm repository:
fuel-asm = "0.43.1"
fuel-tx = "0.43.1"
ethabi = "18.0.0"
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }
prover-core = { path = "./packages/risc0/core" }
methods = { path = "./packages/risc0/methods", package = "methods" }
# Dependencies from fuel-core repository:
fuel-core-types = { version = "0.22.0", default-features = false }

# Dependencies from fuels-rs repository:    
fuels = { version = "0.54.0", features = ["fuel-core-lib"] }

# Third-party dependencies
anyhow = "1.0.75"
tokio = { version = "1.32.0", features = ["rt", "macros", "full", "sync"] }
hex = "0.4.3"
serde = {version = "1.0.188", default-features = false}
serde_json = "1.0.104"

# Dependendencies from risc0
bonsai-sdk = { git = "https://github.com/risc0/risc0", rev = "1742ef8098d246871055501a0559811c9a8fece4" }
bonsai-ethereum-relay = { git = "https://github.com/risc0/risc0", rev = "1742ef8098d246871055501a0559811c9a8fece4" }
risc0-build = { git = "https://github.com/risc0/risc0", rev = "1742ef8098d246871055501a0559811c9a8fece4" }
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "1742ef8098d246871055501a0559811c9a8fece4", default-features = false }


# Risc0 configurations
# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
