[workspace]
members = [
  "packages/fungible-token/test-deposit-recipient-contract",
  "packages/fungible-token/bridge-fungible-token/implementation",
  "packages/message-predicates/contract-message-predicate",
  "packages/message-predicates/contract-message-receiver",
]
