[workspace]
members = [
  "packages/fungible-token/test-deposit-recipient-contract",
  "packages/fungible-token/bridge-fungible-token",
  "packages/message-predicates/contract-message-predicate",
  "packages/message-predicates/contract-message-receiver",
]

[patch.'https://github.com/fuellabs/sway']
std = { git = "https://github.com/fuellabs/sway", branch = "feat/transaction-policies" }
