[package]
name = "fuel-canary-watchtower"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel canary watchtower"

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.74"
cynic = "2.2"
ethers = "2.0.10"
eyre = "0.3.7"
fuel-core-client = "0.26"
fuels = { workspace = true }
log = "0.4.17"
log4rs = { version = "1.2.0", features = ["config_parsing"]}
reqwest = "0.11.22"
serde = "1.0.152"
serde_json = "1.0.91"
tokio = { workspace = true }
thiserror = { version = "1.0", default-features = false }

tracing-appender = "0.2"
colored = "2.0"
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", features = [  "ansi",
    "env-filter",
    "json",] }
clap = { version = "4.0", features = ["derive", "env"] }
config = { version = "0.14", features = ["toml", "async"] }

[dev-dependencies]
mockall = "0.12.1"

