version: '3.4'

services:
  l1_chain:
    image: fueldev/l1chain:${DOCKER_TAG_L1_CHAIN:-latest}
    build:
      dockerfile: ./docker/l1-chain/Dockerfile
      # Use build context of the root directory
      # to allow coping solidity-contracts on Dockerfile
      context: ../
    env_file:
      - ./envs/l1_chain.env
      - ./envs/ports.env
    ports:
      # expose the service to the host for integration testing
      - ${L1_CHAIN_HTTP_PORT:-8545}:9545
      - ${DEPLOYMENTS_PORT:-8080}:8081
    stop_grace_period: 1s
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -f http://l1_chain:${L1_CHAIN_HTTP_PORT:-9545} || exit 1',
        ]
      interval: 3s
      timeout: 5s
      retries: 5
    profiles:
      - bridge

  fuel_core:
    depends_on:
      - l1_chain
    image: fueldev/fuelcore:${DOCKER_TAG_FUEL_CORE:-latest}
    platform: linux/amd64
    build:
      context: ./fuel-core/
    env_file:
      - ./envs/fuel_core.env
    environment:
      L1_CHAIN_HTTP: http://l1_chain:9545
      DEPLOYMENTS_HTTP: http://l1_chain:8081/deployments.local.json
      RUST_LOG: debug
      DEBUG: true
    ports:
      # expose the service to the host for integration testing
      - ${FUEL_CORE_HTTP_PORT:-4000}:4001
    stop_grace_period: 1s
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://fuel_core:4001/v1/health || exit 1']
      interval: 3s
      timeout: 5s
      retries: 5
    profiles:
      - bridge

  fuel_block_commiter:
    depends_on:
      - fuel_core
    image: fueldev/block-committer:${DOCKER_TAG_FUEL_CORE:-latest}
    platform: linux/amd64
    build:
      context: ./block-committer/
    env_file:
      - ./envs/block_committer.env
    environment:
      ETHEREUM_RPC: ws://l1_chain:9545/
      FUEL_GRAPHQL_ENDPOINT: http://fuel_core:4001/v1
      DEPLOYMENTS_HTTP: http://l1_chain:8081/deployments.local.json
    ports:
      # expose the service to the host for integration testing
      - ${COMMITTER_HTTP_PORT:-8888}:8888
    stop_grace_period: 1s
    profiles:
      - bridge

  fuel_canary_watchtower:
    image: fueldev/fuel_canary_watchtower:${DOCKER_TAG_FUEL_CANARY_WATCHTOWER:-latest}
    build:
      dockerfile: ./docker/fuel-canary-watchtower/Dockerfile
      context: ../
    env_file:
      - ./envs/fuel_canary_watchtower.env
    environment:
      FUEL_GRAPHQL_ENDPOINT: http://fuel_core:4001/v1
      ETHEREUM_RPC: http://l1_chain:9545
    stop_grace_period: 1s
    depends_on:
      l1_chain:
        condition: service_healthy
      fuel_core:
        condition: service_healthy
    profiles:
      - watchtower
