[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "proxy"

[dependencies]
interface = { path = "../interface" }
src_20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.2.2" }
contract_message_receiver = { path = "../../../message-predicates/contract-message-receiver" }