[package]
name = "fuel-contract-message-predicate"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Script and predicate for relaying contract messages."

[dependencies]
# Dependencies from the `fuel-vm` repository:
fuel-asm = { workspace = true }
fuel-tx = { workspace = true }

sha2 = "0.10.6"

[dev-dependencies]
fuel-core-types = { workspace = true }
fuels = { workspace = true }
hex = { workspace = true }
insta = "1.28"
tokio = { workspace = true }

[build-dependencies]

# Dependencies from the `fuel-vm` repository:
fuel-asm = { workspace = true }
fuel-tx = { workspace = true }
sha2 = "0.10.6"

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
